/*interface firstNation {
  value: string;
  viewValue: string
}

export const firstNationElem: firstNation[] = [
  {value: "604", viewValue: "?AKISQ'NUK FIRST NATION (FORMERLY COLUMBIA LAKE)"},
  {value: "709", viewValue: "?ESDILAGH FIRST NATION (FORMERLY ALEXANDRA)"},
  {value: "1",   viewValue: "ABEGWEIT BAND"},
  {value: "18",  viewValue: "ACADIA BAND"},
  {value: "684", viewValue: "ADAMS LAKE"},
  {value: "659", viewValue: "AHOUSAHT"},
  {value: "406", viewValue: "AHTAHKAKOOP"},
  {value: "558", viewValue: "AITCHELITZ"},
  {value: "755", viewValue: "AKLAVIK BAND"},
  {value: "142", viewValue: "ALBANY FIRST NATION (AT FORT ALBANY)"},
  {value: "160", viewValue: "ALDERVILLE FIRST NATION"},
  {value: "438", viewValue: "ALEXANDER BAND"},
  {value: "437", viewValue: "ALEXIS NAKOTA SIOUX NATION"},
  {value: "74",  viewValue: "ALGONQUINS OF BARRIERE LAKE"},
  {value: "163", viewValue: "ALGONQUINS OF PIKWAKANAGAN FIRST NATION"},
  {value: "194", viewValue: "ANIMBIIGOO ZAAGI'IGAN ANISHINAABEK"},
  {value: "153", viewValue: "ANISHINABE OF WAUZHUSHK ONIGUM FIRST NATION"},
  {value: "125", viewValue: "ANISHNAABEG OF NAONGASHIING"},
  {value: "20",  viewValue: "ANNAPOLIS VALLEY BAND"},
  {value: "685", viewValue: "ASHCROFT"},
  {value: "463", viewValue: "ATHABASCA CHIPEWYAN FIRST NATION"},
  {value: "143", viewValue: "ATTAWAPISKAT FIRST NATION"},
  {value: "308", viewValue: "BARREN LANDS BAND"},
  {value: "198", viewValue: "BATCHEWANA FIRST NATION"},
  {value: "21",  viewValue: "BEAR RIVER BAND"},
  {value: "369", viewValue: "BEARDY'S & OKEMASIS"},
  {value: "207", viewValue: "BEARSKIN LAKE FIRST NATION"},
  {value: "141", viewValue: "BEAUSOLEIL FIRST NATION"},
  {value: "445", viewValue: "BEAVER FIRST NATION"},
  {value: "460", viewValue: "BEAVER LAKE CREE NATION"},
  {value: "640", viewValue: "BEECHER BAY"},
  {value: "266", viewValue: "BERENS RIVER BAND"},
  {value: "124", viewValue: "BIG GRASSY FIRST NATION"},
  {value: "404", viewValue: "BIG RIVER"},
  {value: "458", viewValue: "BIGSTONE CREE NATION"},
  {value: "197", viewValue: "BIINJITIWAABIK ZAAGING ANISHINAABEK"},
  {value: "730", viewValue: "BINCHE WHUT'EN"},
  {value: "196", viewValue: "BINGWI NEYAASHI ANISHINAABEK"},
  {value: "403", viewValue: "BIRCH NARROWS FIRST NATION"},
  {value: "284", viewValue: "BIRDTAIL SIOUX BAND"},
  {value: "359", viewValue: "BLACK LAKE"},
  {value: "260", viewValue: "BLACK RIVER FIRST NATION BAND"},
  {value: "435", viewValue: "BLOOD BAND"},
  {value: "267", viewValue: "BLOODVEIN BAND"},
  {value: "547", viewValue: "BLUEBERRY RIVER"},
  {value: "686", viewValue: "BONAPARTE"},
  {value: "700", viewValue: "BOOTHROYD"},
  {value: "701", viewValue: "BOSTON BAR FIRST NATION"},
  {value: "590", viewValue: "BRIDGE RIVER"},
  {value: "261", viewValue: "BROKENHEAD OJIBWAY NATION BAND"},
  {value: "228", viewValue: "BRUNSWICK HOUSE FIRST NATION"},
  {value: "4",   viewValue: "BUCTOUCHE MICMAC NATION"},
  {value: "265", viewValue: "BUFFALO POINT FIRST NATION BAND"},
  {value: "398", viewValue: "BUFFALO RIVER DENE NATION"},
  {value: "301", viewValue: "BUNIBONIBEE CREE NATION BAND"},
  {value: "619", viewValue: "BURNS LAKE"},
  {value: "549", viewValue: "BURRARD"},
  {value: "165", viewValue: "CALDWELL FIRST NATION"},
  {value: "622", viewValue: "CAMPBELL RIVER"},
  {value: "713", viewValue: "CANIM LAKE"},
  {value: "394", viewValue: "CANOE LAKE"},
  {value: "289", viewValue: "CANUPAWAKPA DAKOTA FIRST NATION BAND"},
  {value: "623", viewValue: "CAPE MUDGE"},
  {value: "491", viewValue: "CARCROSS/TAGISH FIRST NATION"},
  {value: "378", viewValue: "CARRY THE KETTLE"},
  {value: "216", viewValue: "CAT LAKE FIRST NATION"},
  {value: "591", viewValue: "CAYOOSE CREEK"},
  {value: "507", viewValue: "CHAMPAGNE & AISHIHIK FIRST NATIONS"},
  {value: "221", viewValue: "CHAPLEAU CREE FIRST NATION"},
  {value: "229", viewValue: "CHAPLEAU OJIBWAY FIRST NATION"},
  {value: "583", viewValue: "CHAWATHIL"},
  {value: "584", viewValue: "CHEAM"},
  {value: "309", viewValue: "CHEMAWAWIN CREE NATION BAND"},
  {value: "620", viewValue: "CHESLATTA CARRIER NATION"},
  {value: "470", viewValue: "CHIPEWYAN PRAIRIE FIRST NATION"},
  {value: "171", viewValue: "CHIPPEWAS OF KETTLE & STONY POINT FIRST NATION"},
  {value: "122", viewValue: "CHIPPEWAS OF NAWASH FIRST NATION"},
  {value: "139", viewValue: "CHIPPEWAS OF RAMA FIRST NATION"},
  {value: "172", viewValue: "CHIPPEWAS OF SARNIA FIRST NATION"},
  {value: "166", viewValue: "CHIPPEWAS OF THE THAMES FIRST NATION"},
  {value: "401", viewValue: "CLEARWATER RIVER DENE"},
  {value: "173", viewValue: "COCKBURN ISLAND FIRST NATION"},
  {value: "464", viewValue: "COLD LAKE FIRST NATIONS BAND"},
  {value: "693", viewValue: "COLDWATER"},
  {value: "85",  viewValue: "CONSEIL DE BANDE DE BETSIAMITES"},
  {value: "62",  viewValue: "CONSEIL DE BANDE DE KITCISAKIK"},
  {value: "71",  viewValue: "CONSEIL DE BANDE DES ABÉNAKIS DE WÔLINAK"},
  {value: "79",  viewValue: "CONSEIL DE BANDE DES ATIKAMEWK D'OPITCIWAN"},
  {value: "82",  viewValue: "CONSEIL DE BANDE DES INNUS DE EKUANITSHIT"},
  {value: "86",  viewValue: "CONSEIL DE BANDE DES MONTAGNAIS ESSIPIT"},
  {value: "72",  viewValue: "CONSEIL DE BANDE D'ODANAK"},
  {value: "63",  viewValue: "CONSEIL DE BANDE LA NATION ANISHNABE DU LAC SIMON"},
  {value: "50",  viewValue: "CONSEIL DE LA NATION HURONNE-WENDAT"},
  {value: "55",  viewValue: "CONSEIL DE LA PREMIÈRE NATION ABITIBIWINNI"},
  {value: "77",  viewValue: "CONSEIL DE WEMOTACI"},
  {value: "78",  viewValue: "CONSEIL DES ATIKAMEKW DE MANAWAN"},
  {value: "83",  viewValue: "CONSEIL DES MONTAGNAIS DE NATASHQUAN"},
  {value: "88",  viewValue: "CONSEIL DES MONTAGNAIS DE PAKUA SHIPI"},
  {value: "84",  viewValue: "CONSEIL DES MONTAGNAIS UNAMEN SHIPU"},
  {value: "182", viewValue: "CONSTANCE LAKE FIRST NATION"},
  {value: "694", viewValue: "COOK'S FERRY"},
  {value: "366", viewValue: "COTE FIRST NATION #366"},
  {value: "126", viewValue: "COUCHICHING FIRST NATION"},
  {value: "70",  viewValue: "COUNCIL OF KAHNAWAKE"},
  {value: "361", viewValue: "COWESSESS"},
  {value: "642", viewValue: "COWICHAN"},
  {value: "58",  viewValue: "CREE NATION OF CHISASIBI"},
  {value: "75",  viewValue: "CREE NATION OF MISTISSINI"},
  {value: "60",  viewValue: "CREE NATION OF WEMINDJI"},
  {value: "276", viewValue: "CROSS LAKE BAND OF INDIANS"},
  {value: "350", viewValue: "CUMBERLAND HOUSE CREE NATION"},
  {value: "161", viewValue: "CURVE LAKE FIRST NATION"},
  {value: "288", viewValue: "DAKOTA PLAINS BAND"},
  {value: "295", viewValue: "DAKOTA TIPI BAND"},
  {value: "635", viewValue: "DA'NAXDA'XW FIRST NATION (FORMERLY TANAKTEUK)"},
  {value: "316", viewValue: "DAUPHIN RIVER BAND"},
  {value: "389", viewValue: "DAY STAR"},
  {value: "504", viewValue: "DEASE RIVER"},
  {value: "237", viewValue: "DEER LAKE FIRST NATION"},
  {value: "752", viewValue: "DENE COMMUNITY COUNCIL"},
  {value: "448", viewValue: "DENE THA' BAND"},
  {value: "762", viewValue: "DENINOO COMMUNITY COUNCIL"},
  {value: "662", viewValue: "DITIDAHT"},
  {value: "548", viewValue: "DOIG RIVER"},
  {value: "218", viewValue: "DOKIS FIRST NATION"},
  {value: "561", viewValue: "DOUGLAS"},
  {value: "450", viewValue: "DRIFTPILE FIRST NATION"},
  {value: "451", viewValue: "DUNCAN'S FIRST NATION"},
  {value: "636", viewValue: "DZAWADA'ENUXW FIRST NATION"},
  {value: "183", viewValue: "EABAMETOONG FIRST NATION"},
  {value: "148", viewValue: "EAGLE LAKE FIRST NATION"},
  {value: "57",  viewValue: "EASTMAIN BAND COUNCIL"},
  {value: "280", viewValue: "EBB AND FLOW BAND"},
  {value: "7",   viewValue: "EEL GROUND BAND"},
  {value: "8",   viewValue: "EEL RIVER BAR FIRST NATION"},
  {value: "634", viewValue: "EHATTESAHT"},
  {value: "3",   viewValue: "ELSIPOGTOG FIRST NATION"},
  {value: "400", viewValue: "ENGLISH RIVER FIRST NATION"},
  {value: "440", viewValue: "ENOCH CREE NATION #440"},
  {value: "443", viewValue: "ERMINESKIN TRIBE"},
  {value: "5",   viewValue: "ESGENOOPETITJ FIRST NATION"},
  {value: "711", viewValue: "ESK’ETEMC (FORMERLY ALKALI LAKE)"},
  {value: "23",  viewValue: "ESKASONI BAND"},
  {value: "644", viewValue: "ESQUIMALT"},
  {value: "495", viewValue: "FIRST NATION OF NACHO NYAK DUN"},
  {value: "264", viewValue: "FISHER RIVER BAND"},
  {value: "390", viewValue: "FISHING LAKE FIRST NATION"},
  {value: "759", viewValue: "FITZ/SMITH NATIVE BAND"},
  {value: "395", viewValue: "FLYING DUST FIRST NATION"},
  {value: "227", viewValue: "FLYING POST FIRST NATION"},
  {value: "351", viewValue: "FOND DU LAC"},
  {value: "262", viewValue: "FORT ALEXANDER BAND"},
  {value: "9",   viewValue: "FORT FOLLY BAND"},
  {value: "754", viewValue: "FORT FRANKLIN BAND COUNCIL"},
  {value: "758", viewValue: "FORT LIARD BAND COUNCIL"},
  {value: "467", viewValue: "FORT MCKAY FIRST NATION"},
  {value: "468", viewValue: "FORT MCMURRAY 468 FIRST NATION"},
  {value: "543", viewValue: "FORT NELSON"},
  {value: "750", viewValue: "FORT NORMAN BAND COUNCIL"},
  {value: "760", viewValue: "FORT PROVIDENCE BAND COUNCIL"},
  {value: "215", viewValue: "FORT SEVERN FIRST NATION"},
  {value: "757", viewValue: "FORT SIMPSON BAND COUNCIL"},
  {value: "187", viewValue: "FORT WILLIAM FIRST NATION"},
  {value: "305", viewValue: "FOX LAKE BAND"},
  {value: "465", viewValue: "FROG LAKE BAND"},
  {value: "294", viewValue: "GAMBLER FIRST NATION"},
  {value: "297", viewValue: "GARDEN HILL FIRST NATIONS BAND"},
  {value: "199", viewValue: "GARDEN RIVER FIRST NATION"},
  {value: "138", viewValue: "GEORGINA ISLAND FIRST NATION"},
  {value: "185", viewValue: "GINOOGAMING FIRST NATION"},
  {value: "531", viewValue: "GITANMAAX"},
  {value: "537", viewValue: "GITANYOW (FORMERLY KITWANCOOL)"},
  {value: "535", viewValue: "GITSEGUKLA"},
  {value: "536", viewValue: "GITWANGAK"},
  {value: "672", viewValue: "GITXAALA NATION (FORMERLY KITKATLA)"},
  {value: "533", viewValue: "GLEN VOWELL"},
  {value: "30",  viewValue: "GLOOSCAP FIRST NATION"},
  {value: "296", viewValue: "GOD'S LAKE FIRST NATION BAND"},
  {value: "391", viewValue: "GORDON"},
  {value: "149", viewValue: "GRASSY NARROWS FIRST NATION"},
  {value: "188", viewValue: "GULL BAY FIRST NATION"},
  {value: "724", viewValue: "GWA'SALA-NAKWAXDA'XW"},
  {value: "627", viewValue: "GWAWAENUK TRIBE (FORMERLY KWA-WA-AINEUK)"},
  {value: "997", viewValue: "GWICH'IN TRIBAL COUNCIL"},
  {value: "534", viewValue: "HAGWILGET FIRST NATION GOVERNMENT"},
  {value: "676", viewValue: "HAISLA NATION (FORMERLY KITAMAAT)"},
  {value: "645", viewValue: "HALALT"},
  {value: "546", viewValue: "HALFWAY RIVER"},
  {value: "675", viewValue: "HARTLEY BAY"},
  {value: "352", viewValue: "HATCHET LAKE"},
  {value: "761", viewValue: "HAY RIVER DENE BAND"},
  {value: "469", viewValue: "HEART LAKE BAND"},
  {value: "538", viewValue: "HEILTSUK"},
  {value: "231", viewValue: "HENVEY INLET FIRST NATION"},
  {value: "661", viewValue: "HESQUIAHT"},
  {value: "162", viewValue: "HIAWATHA FIRST NATION"},
  {value: "703", viewValue: "HIGH BAR"},
  {value: "263", viewValue: "HOLLOW WATER BAND"},
  {value: "552", viewValue: "HOMALCO"},
  {value: "449", viewValue: "HORSE LAKE FIRST NATION"},
  {value: "664", viewValue: "HUPA¿ASATH FIRST NATION (FORMERLY OPETCHESAHT)"},
  {value: "663", viewValue: "HUU-AY-AHT FIRST NATION (FORMERLY OHIAHT)"},
  {value: "10",  viewValue: "INDIAN ISLAND BAND"},
  {value: "80",  viewValue: "INNU TAKUAIKAN UASHAT MAK MANI-UTENAM"},
  {value: "999", viewValue: "INUVIALUIT LAND ADMINISTRATION"},
  {value: "780", viewValue: "INUVIK DENE BAND COUNCIL"},
  {value: "683", viewValue: "ISKUT"},
  {value: "154", viewValue: "ISKUTEWISAKAYGUN #39 INDEPENDENT FIRST NATION"},
  {value: "397", viewValue: "ISLAND LAKE FIRST NATION"},
  {value: "370", viewValue: "JAMES SMITH"},
  {value: "399", viewValue: "JOSEPH BIGHEAD"},
  {value: "624", viewValue: "K’ÓMOKS FIRST NATION"},
  {value: "638", viewValue: "KA:'YU:'K'T'H/CHE:K:TLAS7ET'H' FIRST NATIONS"},
  {value: "362", viewValue: "KAHKEWISTAHAW"},
  {value: "704", viewValue: "KANAKA BAR"},
  {value: "452", viewValue: "KAPAWE'NO FIRST NATION"},
  {value: "210", viewValue: "KASABONIKA LAKE FIRST NATION"},
  {value: "563", viewValue: "KATZIE"},
  {value: "393", viewValue: "KAWACATOOSE"},
  {value: "65",  viewValue: "KEBAOWEK FIRST NATION"},
  {value: "367", viewValue: "KEESEEKOOSE"},
  {value: "286", viewValue: "KEESEEKOOWENIN BAND"},
  {value: "325", viewValue: "KEE-WAY-WIN FIRST NATION"},
  {value: "466", viewValue: "KEHEWIN FIRST NATION"},
  {value: "368", viewValue: "KEY"},
  {value: "212", viewValue: "KINGFISHER LAKE FIRST NATION"},
  {value: "11",  viewValue: "KINGSCLEAR BAND"},
  {value: "377", viewValue: "KINISTIN was Kinistino"},
  {value: "268", viewValue: "KINONJEOSHTEGON FIRST NATION BAND"},
  {value: "532", viewValue: "KISPIOX"},
  {value: "540", viewValue: "KITASOO"},
  {value: "209", viewValue: "KITCHENUHMAYKOOSIB INNINUWUG"},
  {value: "73",  viewValue: "KITIGAN ZIBI ANISHINABEG (MANIWAKI)"},
  {value: "680", viewValue: "KITSELAS"},
  {value: "681", viewValue: "KITSUMKALUM"},
  {value: "553", viewValue: "KLAHOOSE FIRST NATION"},
  {value: "503", viewValue: "KLUANE FIRST NATION"},
  {value: "721", viewValue: "KLUSKUS"},
  {value: "610", viewValue: "KWADACHA (FORMERLY FORT WARE)"},
  {value: "626", viewValue: "KWAKIUTL"},
  {value: "500", viewValue: "KWANLIN DUN FIRST NATION"},
  {value: "564", viewValue: "KWANTLEN FIRST NATIONS (FORMERLY LANGLEY)"},
  {value: "580", viewValue: "KWAW-KWAW-A-PILT"},
  {value: "628", viewValue: "KWIAKAH"},
  {value: "625", viewValue: "KWICKSUTAINEUK-AH-KWAW-AH-MISH"},
  {value: "560", viewValue: "KWIKWETLAM FIRST NATION (FORMERLY COQUITLAM)"},
  {value: "87",  viewValue: "LA NATION INNU MATIMEKUSH-LAC JOHN"},
  {value: "189", viewValue: "LAC DES MILLE LACS FIRST NATION"},
  {value: "127", viewValue: "LAC LA CROIX FIRST NATION"},
  {value: "353", viewValue: "LAC LA RONGE"},
  {value: "205", viewValue: "LAC SEUL FIRST NATION"},
  {value: "607", viewValue: "LAKE BABINE NATION"},
  {value: "271", viewValue: "LAKE MANITOBA BAND"},
  {value: "275", viewValue: "LAKE ST. MARTIN BAND"},
  {value: "674", viewValue: "LAX KW'ALAAMS"},
  {value: "2",   viewValue: "LENNOX ISLAND BAND"},
  {value: "579", viewValue: "LEQ'Á:MEL FIRST NATION (FORMERLY LAKAHAHMEN)"},
  {value: "611", viewValue: "LHEIDLI T'ENNEH NATION (FORMERLY LHEIT LIT'EN)"},
  {value: "715", viewValue: "LHTAKO DENE NATION (FORMERLY RED BLUFF)"},
  {value: "502", viewValue: "LIARD RIVER"},
  {value: "51",  viewValue: "LISTUGUJ MI’GMAQ GOVERNMENT"},
  {value: "379", viewValue: "LITTLE BLACK BEAR"},
  {value: "270", viewValue: "LITTLE GRAND RAPIDS BAND"},
  {value: "340", viewValue: "LITTLE PINE"},
  {value: "447", viewValue: "LITTLE RED RIVER CREE NATION"},
  {value: "492", viewValue: "LITTLE SALMON/CARMACKS FIRST NATION"},
  {value: "274", viewValue: "LITTLE SASKATCHEWAN BAND"},
  {value: "689", viewValue: "LITTLE SHUSWAP LAKE"},
  {value: "184", viewValue: "LONG LAKE #58 FIRST NATION"},
  {value: "287", viewValue: "LONG PLAIN BAND"},
  {value: "67",  viewValue: "LONG POINT FIRST NATIONS"},
  {value: "476", viewValue: "LOON RIVER CREE"},
  {value: "439", viewValue: "LOUIS BULL BAND"},
  {value: "606", viewValue: "LOWER KOOTENAY"},
  {value: "695", viewValue: "LOWER NICOLA"},
  {value: "598", viewValue: "LOWER SIMILKAMEEN"},
  {value: "341", viewValue: "LUCKY MAN"},
  {value: "646", viewValue: "LYACKSON"},
  {value: "705", viewValue: "LYTTON"},
  {value: "6",  viewValue: "MADAWASKA MALISEET FIRST NATION"},
  {value: "174", viewValue: "MAGNETEWAN FIRST NATION"},
  {value: "396", viewValue: "MAKWA SAHGAIEHCAN FIRST NATION"},
  {value: "647", viewValue: "MALAHAT NATION"},
  {value: "629", viewValue: "MAMALILIKULLA-QWE'QWA'SOT'EM"},
  {value: "302", viewValue: "MANTO SIPI CREE NATION BAND"},
  {value: "328", viewValue: "MARCEL COLOMB FIRST NATION BAND"},
  {value: "186", viewValue: "MARTIN FALLS FIRST NATION"},
  {value: "219", viewValue: "MATACHEWAN FIRST NATION"},
  {value: "311", viewValue: "MATHIAS COLOMB BAND"},
  {value: "565", viewValue: "MATSQUI FIRST NATION"},
  {value: "226", viewValue: "MATTAGAMI FIRST NATION"},
  {value: "181", viewValue: "M'CHIGEENG FIRST NATION"},
  {value: "618", viewValue: "MCLEOD LAKE"},
  {value: "26",  viewValue: "MEMBERTOU BAND"},
  {value: "14",  viewValue: "METEPENAGIAG MI'KMAQ NATION"},
  {value: "673", viewValue: "METLAKATLA"},
  {value: "47",  viewValue: "MIAWPUKEK BAND"},
  {value: "225", viewValue: "MICHIPICOTEN FIRST NATION"},
  {value: "52",  viewValue: "MICMACS OF GESCAPEGIAG BAND COUNCIL"},
  {value: "461", viewValue: "MIKISEW CREE FIRST NATION"},
  {value: "27",  viewValue: "MILLBROOK BAND"},
  {value: "203", viewValue: "MISHKEEGOGAMANG FIRST NATION"},
  {value: "310", viewValue: "MISIPAWISTIK CREE NATION"},
  {value: "223", viewValue: "MISSANABIE CREE FIRST NATION"},
  {value: "200", viewValue: "MISSISSAUGA FIRST NATION"},
  {value: "120", viewValue: "MISSISSAUGAS OF NEW CREDIT FIRST NATION"},
  {value: "140", viewValue: "MISSISSAUGAS OF SCUGOG ISLAND FIRST NATION"},
  {value: "374", viewValue: "MISTAWASIS NÊHIYAWAK"},
  {value: "133", viewValue: "MITAANJIGAMIING FIRST NATION"},
  {value: "90",  viewValue: "MOHAWK COUNCIL OF AKWESASNE"},
  {value: "69",  viewValue: "MOHAWK OF KANESATAKE"},
  {value: "164", viewValue: "MOHAWKS OF THE BAY OF QUINTE FIRST NATION"},
  {value: "442", viewValue: "MONTANA BAND"},
  {value: "354", viewValue: "MONTREAL LAKE"},
  {value: "144", viewValue: "MOOSE CREE FIRST NATION"},
  {value: "135", viewValue: "MOOSE DEER POINT FIRST NATION"},
  {value: "342", viewValue: "MOOSOMIN"},
  {value: "167", viewValue: "MORAVIAN OF THE THAMES FIRST NATION"},
  {value: "530", viewValue: "MORICETOWN"},
  {value: "312", viewValue: "MOSAKAHIKEN CREE NATION BAND"},
  {value: "343", viewValue: "MOSQUITO-GRIZZLY BEAR'S HEAD"},
  {value: "557", viewValue: "MOUNT CURRIE"},
  {value: "630", viewValue: "MOWACHAHT/MUCHALAHT"},
  {value: "168", viewValue: "MUNSEE-DELEWARE NATION FIRST NATION"},
  {value: "381", viewValue: "MUSCOWPETUNG"},
  {value: "32",  viewValue: "MUSHUAU INNU FIRST NATION"},
  {value: "375", viewValue: "MUSKEG LAKE"},
  {value: "371", viewValue: "MUSKODAY FIRST NATION"},
  {value: "392", viewValue: "MUSKOWEKWAN BAND"},
  {value: "213", viewValue: "MUSKRAT DAM LAKE FIRST NATION"},
  {value: "550", viewValue: "MUSQUEAM"},
  {value: "612", viewValue: "NADLEH WHUTEN (FORMERLY FRASER LAKE)"},
  {value: "128", viewValue: "NAICATCHEWENIN  FIRST NATION"},
  {value: "614", viewValue: "NAK'AZDLI"},
  {value: "631", viewValue: "NAMGIS FIRST NATION (FORMERLY NIMPKISH)"},
  {value: "649", viewValue: "NANOOSE"},
  {value: "81",  viewValue: "NASKAPIS NATION OF KAWAWACHIKAMACH"},
  {value: "720", viewValue: "NAZK0"},
  {value: "726", viewValue: "NEE-TAHI-BUHN"},
  {value: "380", viewValue: "NEKANEET"},
  {value: "59",  viewValue: "NEMASKA BAND COUNCIL"},
  {value: "239", viewValue: "NESKANTAGA FIRST NATION"},
  {value: "690", viewValue: "NESKONLITH (FORMERLY NESKAINLITH)"},
  {value: "696", viewValue: "NICOMEN"},
  {value: "129", viewValue: "NIGIGOONSIMINIKAANING FIRST NATION"},
  {value: "147", viewValue: "NIISAACHEWAN ANISHINAABE NATION"},
  {value: "220", viewValue: "NIPISSING FIRST NATION"},
  {value: "313", viewValue: "NISICHAWAYASIHK CREE NATION BAND"},
  {value: "699", viewValue: "NOOAITCH"},
  {value: "204", viewValue: "NORTH CARIBOU LAKE FIRST NATION"},
  {value: "238", viewValue: "NORTH SPIRIT LAKE FIRST NATION"},
  {value: "317", viewValue: "NORTHLANDS DENESULINE FIRST NATION"},
  {value: "151", viewValue: "NORTHWEST ANGLE #33 FIRST NATION"},
  {value: "152", viewValue: "NORTHWEST ANGLE #37 FIRST NATION"},
  {value: "278", viewValue: "NORWAY HOUSE CREE NATION BAND"},
  {value: "556", viewValue: "N'QUATQUA (FORMERLY ANDERSON LAKE)"},
  {value: "639", viewValue: "NUCHATLAHT"},
  {value: "539", viewValue: "NUXALK NATION"},
  {value: "408", viewValue: "OCEAN MAN"},
  {value: "363", viewValue: "OCHAPOWACE"},
  {value: "279", viewValue: "O-CHI-CHAK-KO-SIPI FIRST NATION BAND"},
  {value: "431", viewValue: "O'CHIESE BAND"},
  {value: "258", viewValue: "OJIBWAY NATION OF SAUGEEN FIRST NATION"},
  {value: "131", viewValue: "OJIBWAYS OF ONIGAMING FIRST NATION"},
  {value: "180", viewValue: "OJIBWAYS OF SUCKER CREEK FIRST NATION"},
  {value: "192", viewValue: "OJIBWAYS OF THE PIC RIVER FIRST NATION"},
  {value: "616", viewValue: "OKANAGAN"},
  {value: "382", viewValue: "OKANESE"},
  {value: "669", viewValue: "OLD MASSET VILLAGE COUNCIL"},
  {value: "373", viewValue: "ONE ARROW"},
  {value: "344", viewValue: "ONION LAKE"},
  {value: "169", viewValue: "ONYOTA'A:KA FIRST NATION"},
  {value: "315", viewValue: "OPASKWAYAK CREE NATION BAND"},
  {value: "318", viewValue: "O-PIPON-NA-PIWIN CREE NATION BAND"},
  {value: "692", viewValue: "OREGON JACK CREEK"},
  {value: "12",  viewValue: "OROMOCTO BAND"},
  {value: "596", viewValue: "OSOYOOS"},
  {value: "541", viewValue: "OWEEKENO"},
  {value: "13",  viewValue: "PABINEAU BAND"},
  {value: "658", viewValue: "PACHEEDAHT FIRST NATION"},
  {value: "19",  viewValue: "PAQTNKEK MI'KMAW NATION"},
  {value: "106", viewValue: "PARCS CANADA"},
  {value: "383", viewValue: "PASQUA FIRST NATION #79"},
  {value: "327", viewValue: "PAUINGASSI FIRST NATION"},
  {value: "441", viewValue: "PAUL BAND"},
  {value: "652", viewValue: "PAUQUACHIN"},
  {value: "191", viewValue: "PAYS PLAT FIRST NATION"},
  {value: "384", viewValue: "PEEPEEKISIS"},
  {value: "269", viewValue: "PEGUIS BAND"},
  {value: "405", viewValue: "PELICAN LAKE"},
  {value: "650", viewValue: "PENELAKUT"},
  {value: "597", viewValue: "PENTICTON"},
  {value: "355", viewValue: "PETER BALLANTYNE CREE NATION"},
  {value: "586", viewValue: "PETERS"},
  {value: "409", viewValue: "PHEASANT RUMP NAKOTA BAND"},
  {value: "385", viewValue: "PIAPOT"},
  {value: "195", viewValue: "PIC MOBERT FIRST NATION"},
  {value: "24",  viewValue: "PICTOU LANDING BAND"},
  {value: "436", viewValue: "PIIKANI NATION"},
  {value: "208", viewValue: "PIKANGIKUM FIRST NATION"},
  {value: "272", viewValue: "PINAYMOOTANG FIRST NATION BAND"},
  {value: "282", viewValue: "PINE CREEK BAND"},
  {value: "585", viewValue: "POPKUM FIRST NATION"},
  {value: "236", viewValue: "POPLAR HILL FIRST NATION"},
  {value: "277", viewValue: "POPLAR RIVER FIRST NATION BAND"},
  {value: "22",  viewValue: "POTLOTEK FIRST NATION"},
  {value: "345", viewValue: "POUNDMAKER"},
  {value: "76",  viewValue: "PREMIÈRE NATION DES PEKUAKAMIULNUATSH"},
  {value: "54",  viewValue: "PREMIÈRE NATION WOLASTOQIYIK (MALÉCITE) WAHSIPEKUK"},
  {value: "544", viewValue: "PROPHET RIVER FIRST NATION"},
  {value: "651", viewValue: "QUALICUM FIRST NATION"},
  {value: "633", viewValue: "QUATSINO"},
  {value: "130", viewValue: "RAINY RIVER FIRST NATION"},
  {value: "356", viewValue: "RED EARTH"},
  {value: "346", viewValue: "RED PHEASANT"},
  {value: "193", viewValue: "RED ROCK FIRST NATION"},
  {value: "300", viewValue: "RED SUCKER LAKE BAND"},
  {value: "291", viewValue: "ROLLING RIVER BAND"},
  {value: "273", viewValue: "ROSEAU RIVER ANISHINABE FIRST NATION GOVERNMENT BAND"},
  {value: "214", viewValue: "SACHIGO LAKE FIRST NATION"},
  {value: "462", viewValue: "SADDLE LAKE BAND"},
  {value: "179", viewValue: "SAGAMOK ANISHNAWBEK FIRST NATION"},
  {value: "615", viewValue: "SAIK'UZ FIRST NATION (FORMERLY STONY CREEK)"},
  {value: "15",  viewValue: "SAINT MARY'S BAND"},
  {value: "567", viewValue: "SAMAHQUAM"},
  {value: "444", viewValue: "SAMSON BAND"},
  {value: "283", viewValue: "SANDY BAY BAND"},
  {value: "211", viewValue: "SANDY LAKE FIRST NATION"},
  {value: "314", viewValue: "SAPOTAWEYAK CREE NATION BAND"},
  {value: "123", viewValue: "SAUGEEN FIRST NATION"},
  {value: "542", viewValue: "SAULTEAU FIRST NATIONS"},
  {value: "347", viewValue: "SAULTEAUX"},
  {value: "454", viewValue: "SAWRIDGE BAND"},
  {value: "303", viewValue: "SAYISI DENE FIRST NATION BAND"},
  {value: "568", viewValue: "SCOWLITZ"},
  {value: "581", viewValue: "SEABIRD ISLAND"},
  {value: "551", viewValue: "SECHELT"},
  {value: "132", viewValue: "SEINE RIVER FIRST NATION"},
  {value: "498", viewValue: "SELKIRK FIRST NATION"},
  {value: "569", viewValue: "SEMIAHMOO"},
  {value: "201", viewValue: "SERPENT RIVER FIRST NATION"},
  {value: "595", viewValue: "SETON LAKE"},
  {value: "698", viewValue: "SHACKAN"},
  {value: "307", viewValue: "SHAMATTAWA FIRST NATION BAND"},
  {value: "137", viewValue: "SHAWANAGA FIRST NATION"},
  {value: "176", viewValue: "SHEGUIANDAH FIRST NATION"},
  {value: "33",  viewValue: "SHESHATSHIU INNU FIRST NATION"},
  {value: "178", viewValue: "SHESHEGWANING FIRST NATION"},
  {value: "155", viewValue: "SHOAL LAKE #40 FIRST NATION"},
  {value: "357", viewValue: "SHOAL LAKE CREE NATION"},
  {value: "605", viewValue: "SHUSWAP"},
  {value: "570", viewValue: "SHXWHÁ:Y VILLAGE (FORMERLY SKWAY)"},
  {value: "587", viewValue: "SHXW'OW'HAMEL FIRST NATION (FORMERLY OHAMIL)"},
  {value: "430", viewValue: "SIKSIKA NATION"},
  {value: "691", viewValue: "SIMPCW FIRST NATION (FORMERLY NORTH THOMPSON)"},
  {value: "290", viewValue: "SIOUX VALLEY DAKOTA NATION BAND"},
  {value: "25",  viewValue: "SIPEKNE'KATIK BAND"},
  {value: "706", viewValue: "SISKA"},
  {value: "244", viewValue: "SIX NATIONS OF GRAND RIVER FIRST NATION"},
  {value: "562", viewValue: "SKATIN NATIONS (FORMERLY SKOOKUM CHUCK)"},
  {value: "582", viewValue: "SKAWAHLOOK FIRST NATION"},
  {value: "687", viewValue: "SKEETCHESTN (FORMERLY DEADMAN'S CREEK)"},
  {value: "670", viewValue: "SKIDEGATE"},
  {value: "729", viewValue: "SKIN TYEE"},
  {value: "571", viewValue: "SKOWKALE"},
  {value: "281", viewValue: "SKOWNAN FIRST NATION BAND"},
  {value: "707", viewValue: "SKUPPAH"},
  {value: "573", viewValue: "SKWAH"},
  {value: "259", viewValue: "SLATE FALLS NATION FIRST NATION"},
  {value: "477", viewValue: "SMITHS LANDING FIRST NATION"},
  {value: "648", viewValue: "SNUNEYMUXW FIRST NATION (FORMERLY NANAIMO)"},
  {value: "656", viewValue: "SONGHEES"},
  {value: "572", viewValue: "SOOWAHLIE"},
  {value: "600", viewValue: "SPLATSIN FIRST NATION"},
  {value: "708", viewValue: "SPUZZUM"},
  {value: "555", viewValue: "SQUAMISH"},
  {value: "574", viewValue: "SQUIALA FIRST NATION"},
  {value: "602", viewValue: "ST. MARY'S"},
  {value: "298", viewValue: "ST. THERESA POINT BAND"},
  {value: "386", viewValue: "STANDING BUFFALO"},
  {value: "387", viewValue: "STAR BLANKET CREE NATION"},
  {value: "613", viewValue: "STELLAT'EN FIRST NATION"},
  {value: "433", viewValue: "STONEY FIRST NATION"},
  {value: "559", viewValue: "STS'AILES (FORMERLY CHEHALIS)"},
  {value: "723", viewValue: "STSWECEM'C XGAT'TEM FIRST NATION (FORMERLY CANOE CREEK)"},
  {value: "455", viewValue: "STURGEON LAKE CREE NATION"},
  {value: "360", viewValue: "STURGEON LAKE FIRST NATION"},
  {value: "641", viewValue: "STZ'UMINUS FIRST NATION (FORMERLY CHEMAINUS)"},
  {value: "456", viewValue: "SUCKER CREEK BAND"},
  {value: "578", viewValue: "SUMAS FIRST NATION"},
  {value: "434", viewValue: "SUNCHILD FIRST NATION"},
  {value: "293", viewValue: "SWAN LAKE BAND"},
  {value: "457", viewValue: "SWAN RIVER FIRST NATION"},
  {value: "348", viewValue: "SWEET GRASS"},
  {value: "508", viewValue: "TA'AN KWACH'AN COUNCIL"},
  {value: "682", viewValue: "TAHLTAN"},
  {value: "608", viewValue: "TAKLA NATION"},
  {value: "501", viewValue: "TAKU RIVER TLINGIT"},
  {value: "446", viewValue: "TALLCREE BAND"},
  {value: "306", viewValue: "TATASKWEYAK CREE NATION BAND"},
  {value: "145", viewValue: "TAYKWA TAGAMOU NATION (AT NEW POST)"},
  {value: "751", viewValue: "TEETL’IT GWICH’IN BAND COUNCIL"},
  {value: "222", viewValue: "TEMAGAMI FIRST NATION"},
  {value: "499", viewValue: "TESLIN TLINGIT COUNCIL"},
  {value: "202", viewValue: "THESSALON FIRST NATION"},
  {value: "349", viewValue: "THUNDERCHILD FIRST NATION"},
  {value: "64",  viewValue: "TIMISKAMING FIRST NATION"},
  {value: "593", viewValue: "T'IT'Q'ET (FORMERLY LILLOOET)"},
  {value: "688", viewValue: "TK’EMLÛPS TE SECWÇPEMC (FORMERLY KAMLOOPS)"},
  {value: "712", viewValue: "TL’ETINQOX-T’IN GOVERNMENT (FORMERLY ANAHAM)"},
  {value: "660", viewValue: "TLAOQUIAHT (FORMERLY CLAYOQUOT)"},
  {value: "632", viewValue: "TLATLASIKWALA"},
  {value: "617", viewValue: "TL'AZT'EN NATIONS (FORMERLY STUART LAKE)"},
  {value: "637", viewValue: "TLOWITSIS TRIBE (FORMERLY TLOWITSIS-MUMTAGILA)"},
  {value: "603", viewValue: "TOBACCO PLAINS"},
  {value: "16",  viewValue: "TOBIQUE BAND"},
  {value: "718", viewValue: "TOOSEY"},
  {value: "292", viewValue: "TOOTINAOWAZIIBEENG TREATY RESERVE BAND"},
  {value: "666", viewValue: "TOQUAHT"},
  {value: "494", viewValue: "TR'ONDËK HWËCH'IN"},
  {value: "643", viewValue: "TS’UUBAA-ASATX"},
  {value: "653", viewValue: "TSARTLIP"},
  {value: "654", viewValue: "TSAWOUT FIRST NATION"},
  {value: "609", viewValue: "TSAY KEH DENE (FORMERLY INGENIKA)"},
  {value: "665", viewValue: "TSESHAHT"},
  {value: "655", viewValue: "TSEYCUM"},
  {value: "710", viewValue: "TSIDELDEL FIRST NATION"},
  {value: "594", viewValue: "TS'KW'AYLAXW FIRST NATION (FORMERLY PAVILION)"},
  {value: "657", viewValue: "T'SOU-KE FIRST NATION (FORMERLY SOOKE)"},
  {value: "432", viewValue: "TSUU T'INA NATION"},
  {value: "998", viewValue: "TUNGAVIK FED. OF NUNAVUT"},
  {value: "575", viewValue: "TZEACHTEN"},
  {value: "667", viewValue: "UCHUCKLESAHT"},
  {value: "668", viewValue: "UCLUELET FIRST NATION"},
  {value: "722", viewValue: "ULKATCHO"},
  {value: "588", viewValue: "UNION BAR"},
  {value: "697", viewValue: "UPPER NICOLA"},
  {value: "599", viewValue: "UPPER SIMILKAMEEN"},
  {value: "496", viewValue: "VUNTUT GWITCHIN FIRST NATION"},
  {value: "150", viewValue: "WABASEEMOONG FIRST NATION"},
  {value: "156", viewValue: "WABAUSKANG FIRST NATION"},
  {value: "157", viewValue: "WABIGOON LAKE OJIBWAY NATION FIRST NATION"},
  {value: "28",  viewValue: "WAGMATCOOK BAND"},
  {value: "232", viewValue: "WAHNAPITAE FIRST NATION"},
  {value: "358", viewValue: "WAHPETON DAKOTA NATION"},
  {value: "134", viewValue: "WAHTA MOHAWK FIRST NATION"},
  {value: "170", viewValue: "WALPOLE ISLAND FIRST NATION"},
  {value: "206", viewValue: "WAPEKEKA FIRST NATION"},
  {value: "323", viewValue: "WAR LAKE FIRST NATION BAND"},
  {value: "299", viewValue: "WASAGAMACK FIRST NATION BAND"},
  {value: "136", viewValue: "WASAUKSING-PARRY ISLAND FIRST NATION"},
  {value: "235", viewValue: "WASHAGAMIS BAY  FIRST NATION"},
  {value: "61",  viewValue: "WASKAGANISH BAND COUNCIL"},
  {value: "56",  viewValue: "WASWANIPI BAND COUNCIL"},
  {value: "402", viewValue: "WATERHEN LAKE"},
  {value: "234", viewValue: "WAWAKAPEWIN FIRST NATION"},
  {value: "285", viewValue: "WAYWAYSEECAPPO FIRST NATION TREATY FOUR - 1874 BAND"},
  {value: "240", viewValue: "WEBEQUIE FIRST NATION"},
  {value: "146", viewValue: "WEENUSK FIRST NATION"},
  {value: "29",  viewValue: "WE'KOQMA'Q FIRST NATION"},
  {value: "545", viewValue: "WEST MOBERLY LAKE"},
  {value: "601", viewValue: "WESTBANK FIRST NATION"},
  {value: "725", viewValue: "WET'SUWET'EN FIRST NATION"},
  {value: "89",  viewValue: "WHAPMAGOOSTUI FIRST NATION"},
  {value: "702", viewValue: "WHISPERING PINES (FORMERLY CLINTON)"},
  {value: "365", viewValue: "WHITE BEAR"},
  {value: "372", viewValue: "WHITECAP DAKOTA/SIOUX FIRST NATION"},
  {value: "158", viewValue: "WHITEFISH BAY  FIRST NATION"},
  {value: "459", viewValue: "WHITEFISH LAKE BAND"},
  {value: "224", viewValue: "WHITEFISH LAKE FIRST NATION"},
  {value: "230", viewValue: "WHITEFISH RIVER FIRST NATION"},
  {value: "190", viewValue: "WHITESAND FIRST NATION"},
  {value: "175", viewValue: "WIKWEMIKONG FIRST NATION"},
  {value: "719", viewValue: "WILLIAMS LAKE FIRST NATION"},
  {value: "407", viewValue: "WITCHEKAN LAKE"},
  {value: "68",  viewValue: "WOLF LAKE BAND COUNCIL"},
  {value: "388", viewValue: "WOOD MOUNTAIN"},
  {value: "474", viewValue: "WOODLAND CREE FIRST NATION"},
  {value: "17",  viewValue: "WOODSTOCK BAND"},
  {value: "217", viewValue: "WUNNUMIN FIRST NATION"},
  {value: "324", viewValue: "WUSKWI SIPIHK FIRST NATION BAND"},
  {value: "716", viewValue: "XAT'SUIL FIRST NATION (FORMERLY SODA CREEK)"},
  {value: "592", viewValue: "XAXLI'P FIRST NATION (FORMERLY FOUNTAIN)"},
  {value: "714", viewValue: "XENI GWET'IN FIRST NATIONS (FORMERLY NEMAIAH VALLEY)"},
  {value: "576", viewValue: "YAKWEAKWIOOSE"},
  {value: "589", viewValue: "YALE"},
  {value: "728", viewValue: "YEKOOCHE"},
  {value: "763", viewValue: "YELLOWKNIVES DENE FIRST NATION"},
  {value: "376", viewValue: "YELLOWQUILL WAS NUT LAKE"},
  {value: "304", viewValue: "YORK FACTORY FIRST NATION BAND"},
  {value: "717", viewValue: "YUNESIT’IN GOVERNMENT (FORMERLY STONE)"},
  {value: "364", viewValue: "ZAGIME ANISHINABEK"}
];
*/