let legendDescriptions: any = {
  'en-CA': {
    allTabsButton: "Toggle all group of layers visible or not visible.",
    allButton: "Toggle all layers visible or not visible.",
    anno: "Annotations",
    basemap: "Toggle the visibility of the Basemap.",
    placeHolder: "Place holder",
    provisionalLine: "The provisional lines consist of the lines required to represent proposed real properties, limited right areas, public right areas and sub-surface areas.  The provisional lines are compiled from pending survey projects.",
    projectEnv: "A survey in progress represents the extent of a proposed or on-going survey project.  The project envelope extent is derived from existing data or is created through red-lining approximate boundaries of a project.  Project envelopes have an unknown accuracy.  Project envelopes are deleted and replaced by a plan envelope when the survey project is completed.",
    placerClaim:"The Placer Claim Base Lines consist of the lines required to create a base line from which the position of Placer Claims can be established.  Placer Claim Base Lines are only used in the Yukon.",
    mineralClaimLine: "The Mineral Claim Location Lines consist of the lines required to establish the position for Quartz Mineral Claims.  Mineral Claim Location Lines are only used in the Yukon.",
    mineralClaimParcel: "Parcel representing a mineral claim extent in the Yukon, the Northwest Territories or Nunavut.",
    yukonFNParcel: "A land parcel that represents the extent of settlement lands as defined in the relevant Final Agreement for each First Nation in the Yukon.",
    yukonInternalarcel: "A Real Property Object representing the spatial extent of a portion of a larger land parcel that cannot be retired.  Internal Parcels may have rights and interests registered against them. They include lots within Yukon First Nation Settlement Land.",
    creenaRight: "A right or interest in category 1A or 1A-N lands of a band or in buildings that are identified graphically on a registry plan.  The Cree-Naskapi number of the right is always assigned by the central land registrar and consists of groups of numbers.",
    creenaLot: "Administrative lots are a portion of category 1A or 1A-N lands as set out in a survey plan prepared by the Surveyor General.  In these cases, the owner of the right in land delimits the extent of his right on the land.",
    creenaParcel: "All lots in Category 1A and 1A1N lands as set out in a survey must be assigned a lot number by the Survey Service of the Quebec Department of Energy and Resources.",
    creenaBlock: "Blocks (portion of a lot) are a system of division of lands to help locate rights rapidly. Blocks are created based on physical indicators on village plans, such as roads, drainage, property lines, etc. The limit of these blocks can be changed at any time to avoid confusion about the identification of a right.",
    irOilGasParcel: "A limited right area representing the extent of an Indian Reserve surface oil and gas right such as a pipeline right-of-way, an access road or a well site.",
    oilGasParcel: "A Sub-surface Area Object representing the spatial extent of a Sub-Surface Oil and Gas Parcel Area to which sub-surface rights may be registered.",
    nad83: "A division of land defined by latitude and longitude to delineate an area for oil and gas purposes and that is further divided into surveyed units.  South of 70° latitude, they are bounded on the East and West by divisions of 15' of longitude and on the North and South by division of 10' of latitude.  North of 70° latitude, they are bounded on the East and West by divisions of 30' of longitude and on the North and South by divisions of 10' of latitude.",
    easement: "A limited right area representing the extent of an easement or right of way affecting a real property.",
    gwichinParcel: "A land parcel that represents the extents of settlement lands as defined in the Gwich’in Comprehensive Land Claim Agreement.",
    inuitOwnedInternal: "A land parcel that represents the extent of a portion of a larger land parcel that cannot be retired.  Internal Parcels may have rights and interests registered against them.  They include parcels within the Inuit Owned Lands.",
    inuvialuitFinalInternal: "A land parcel that represents the extent of a portion of a larger land parcel that cannot be retired.  Internal Parcels may have rights and interests registered against them. They include parcels within the Inuvialuit Final Agreement.",
    sahtu: "A land parcel that represents the extent of settlement lands as defined in the Sahtu Dene and Métis Comprehensive Land Claim Settlement Agreement.",
    saltRiver: "A land parcel that represents the extent of settlement lands as defined in the Salt River First Nation Treaty Settlement Agreement.",
    tlicho: "A land parcel that represents the extent of settlement lands as defined in the Tlicho Land Claims and Self-Government Agreement.",
    landParcel: "Real property representing the extent of a lot or parcel of land against which rights and interests may be registered.",
    inuitOwnedParcel: "A land parcel that represents the extent of settlement lands as defined in the Nunavut Land Claims Agreement.",
    inuvialuitFinalParcel: "A land parcel that represents the extent of settlement lands as defined in the Inuvialuit Final Agreement.",
    indianLand: "Lands reserved for the Indians within the meaning of class 24 of section 91 of the Constitution Act, 1867 but not a reserve within the meaning of the Indian Act.",
    townsite: "Land named and described in Schedule 4 of the Canada National Parks Act.",
    settlementLand: "Place holder",
    nationalPark: "Land named and described in Schedule 1 of the Canada National Parks Act.",
    territorialPark: "Park established and maintained by a territorial government.",
    ntsQuad: "A division of land defined by the National Topographic System (NTS) quad sheets, which divides areas in a systematic pattern and allows parcels to be given a unique parcel identifier.  These quads were originally defined by the NAD27 datum, but are now defined by the NAD83 datum.",
    unresolved: "An active land parcel or interest that cannot be geometrically integrated with other “active” land parcels (i.e. extent or location not well established).  They are only used for Indian Reserves.",
    condo: "Real property representing the extent of a condominium or apartment unit to which rights or interests can be registered.  Condominium common areas are not included within this definition (and are not spatially represented in our data).",
    strataParcel: "Real property  representing the extent of an aboveground or underground 3-D parcel to which interests may be registered.  Strata Parcels are rendered as 2-D parcels within our geospatial databases.",
    protectedArea: "A public right area representing the extent of a protected landscape as a result of the public interest or common good.  These areas can include habitat, wilderness areas and other special management areas.",
    fieldNoteDescription:"Every surveyor shall keep exact and regular field notes of all his surveys under the Canada Lands Surveys Act and shall file them with the Surveyor General in the order of time in which the surveys have been performed. [R.S., 1985, c. L-6, s. 18]",
    indianReserveDescription: "Surrendered lands or a reserve, as those expressions are defined in the Indian Act.",
    indianReserveFNLMDescription: "Lands reserved for Indians within the meaning of section 91(24) of the Constitution Act of 1867 or lands set aside in Yukon for which a First Nation has opted-in to the First Nations Land Management Act.",
    subdivisionDescription: "The extent of an official subdivision.",
    oilAndGasSurveyedSSGDescription: "Unit that consists of the spatial representation of each surveyed unit.  Note that the surveyed unit represents the extent of the unit and not the extent of an oil and gas interest.",
    archivedSurveyLineDescription: "Surveyed lines, established by a land surveyor with stated bearing and distance and references by monuments, that have been superseded.",
    otherSurveyedLineDescription: "Other surveyed lines that provide auxiliary information to better define the location of boundaries.  They consist of the extent of features that need to be represented as lines such as traverse, construction lines or topographic features (shoreline, contour, etc.).",
    lotWithinSettlementDescription: "A land parcel that represents the extent of a portion of a larger land parcel that cannot be retired.  Lots within settlement land may have rights and interests registered against them.  They include parcels within the Yukon First Nation settlement lands.",
    creeLotDescription: "Cree-Naskapi land parcel of category 1A or 1A-N.",
    creeLotOtherDescription: "Cree-Naskapi land parcel outside of Canada Lands.",
    subGasParcelDescription: "Subsurface area representing the extent of a sub-surface oil and gas parcel area to which subsurface rights may be registered.",
    easementOtherDescription: "A limited right area representing the extent of an easement or right of way affecting a real property outside Canada Lands.",
    communityDescription: "The extent of a community in the 3 northern territories as defined by northern legislation.",
    inconclusiveDescription: "A land parcel for which the legal status is not clearly established.  They are only used for Indian Reserves.",
    landParcelOtherDescription: "Real property representing the extent of a lot or parcel of land, that is outside of Canada Lands, against which rights and interests may be registered.",
    groupDescription: "The division of land in the 3 northern territories as defined by plans 60109 CLSR and 79155 CLSR.  This segmentation of land was used to provide a suitable land survey system for the North.  This system has been replaced by quads.",
    landExclusionDescription: "A portion of an Indian Reserve may be excluded from the application of a land code for reasons as stipulated under sections 4.1.4 and 4.1.6 of the Framework Agreement on First Nation Land Management.",
    designationDescription: "Means a reserve or part of a reserve or any interest therein, the legal title to which remains vested in Her Majesty, that has been released or surrendered by the band for whose use and benefit it was set apart.",
    quarterDescription: "A rectilinear cadastral line which more specifically represent the limit of a surveyed township quarter-section.",
  },
  'fr-CA': {
    allTabsButton: "Alterner la visibilité ou non de tous les groupes de couches.",
    allButton: "Alterner la visibilité ou non de toutes les couches.",
    anno: "Annotations",
    basemap: "Basculer la visibilité du fond de carte.",
    placeHolder: "Place holder",
    provisionalLine: "Les lignes provisoires sont celles qui sont nécessaires pour représenter des biens immobiliers, des zones de droits limités, des zones de droits publics et des zones de droits miniers.  Les lignes provisoires sont établies d’après des projets d’arpentage en instance.",
    projectEnv: "Un arpentage en cours représente l’étendue spatiale d’un projet d’arpentage envisagé ou en cours.  L’étendue d’une enveloppe de projet est établie d’après des données existantes ou en délimitant approximativement la zone d’un projet avec une ligne rouge.  L’exactitude des enveloppes de projet est inconnue.  Les enveloppes de projet sont supprimées et remplacées par des enveloppes de plan au terme des projets d’arpentage.",
    placerClaim:"Les lignes de base de claim de placer sont les lignes nécessaires pour produire une ligne de base permettant de situer des claims de placer.  Les lignes de base de claim de placer ne sont utilisées qu’au Yukon.",
    mineralClaimLine: "Les lignes de localisation de claim minier sont les lignes nécessaires pour localiser les claims miniers de quartz.  Les lignes de localisation de claim minier ne sont utilisées qu’au Yukon.",
    mineralClaimParcel: "Parcelle représentant l'étendue d'un claim minier au Yukon, dans les Territoires du Nord-Ouest ou au Nunavut.",
    yukonFNParcel: "Parcelle de terrain représentant l’étendue de terres visées par l'Accord final approprié à chacune des Première Nation du Yukon.",
    yukonInternalarcel: "Objet de bien immobilier représentant l’étendue d’une partie d’une parcelle de terrain plus grande qui ne peut être retirée. Des droits et des intérêts peuvent avoir été enregistrés pour des parcelles internes. Ces dernières comprennent les lots dans terres visées par des règlements avec les Premières nations du Yukon.",
    creenaRight: "Droit ou intérêt visant les terres de la catégorie 1A ou 1A-N d’une bande ou des immeubles désignés graphiquement sur un plan d’enregistrement.  Le numéro rattaché aux droits des Cris et des Naskapis est toujours attribué par le registraire du bureau d’enregistrement central et se compose de groupes de chiffres.",
    creenaLot: "Les lots administratifs consistent en une partie des terres des catégories 1A ou 1A-N figurant dans un plan d’arpentage de l'arpenteur général.  En ce qui les concerne, le titulaire des droits fonciers délimite l’étendue de ses droits sur les terres.",
    creenaParcel: "Tous les lots dans les terres des catégories 1A et 1A1N figurant dans un levé d’arpentage doivent se voir attribuer un numéro de lot par le service d’arpentage du ministère des Ressources naturelles et de la Faune du Québec.",
    creenaBlock: "Les blocs (portion d'un lot) sont un système de division des terres pour aider à localiser rapidement les droits.  Les blocs sont créés en se basant sur des indicateurs physiques sur les plans du village, comme les routes, l'écoulement des eaux, les lignes de propriété, etc.  Les limites de ces blocs peuvent être changées à n'importe quel moment pour éviter la confusion dans l'identification d'un droit.",
    irOilGasParcel: "Zone de droits limités représentant l’étendue de droits pétroliers et gaziers de surface dans une réserve indienne, comme une emprise d’oléoduc ou de gazoduc, une route d’accès ou le site d’un puits.",
    oilGasParcel: "Objet de zone de droits miniers qui représente l’étendue spatiale d’une zone de parcelle de droits pétroliers et gaziers souterrains pour laquelle des droits miniers peuvent être enregistrés.",
    nad83: "Division des terres définie par latitude et longitude pour définir une zone pour les fins d'exploitation pétrolière et gazière.   Elles sont une fois de plus divisées en unités arpentées.  Au sud de 70° de latitude, elles sont délimitées à l'est et à l'ouest en divisions de 15' de longitude et au nord et au sud en divisions de 10' de longitude.  Au nord de 70° de latitude, elles sont délimitées à l'est et à l'ouest en divisions de 30' de longitude et au nord et au sud en divisions de 10' de longitude.",
    easement: "Zone de droits limités représentant l’étendue d’une servitude ou d’une emprise visant un bien immobilier.",
    gwichinParcel: "Parcelle de terrain représentant l’étendue de terres visées par l'Entente sur la revendication territoriale globale des Gwich’in.",
    inuitOwnedInternal: "Parcelle de terrain représentant l’étendue d’une partie d’une parcelle de terrain plus grande qui ne peut être retirée.  Des droits et des intérêts peuvent avoir été enregistrés pour des parcelles internes.  Ces dernières comprennent les parcelles dans les limites de terres inuites.",
    inuvialuitFinalInternal: "Parcelle de terrain représentant l’étendue d’une partie d’une parcelle de terrain plus grande qui ne peut être retirée.  Des droits et des intérêts peuvent avoir été enregistrés pour des parcelles internes.  Ces dernières comprennent les parcelles dans les limites de la Convention  définitive des Inuvialuit.",
    sahtu: "Parcelle de terrain représentant l’étendue de terres visées par l'Entente sur la revendication territoriale globale des Dénés et Métis du Sahtu.",
    saltRiver: "Parcelle de terrain représentant l’étendue de terres visées par l'Entente sur les terres visées par un traité de la Première Nation de Salt River.",
    tlicho: "Parcelle de terrain représentant l’étendue des terres visées par l’Accord sur les revendications territoriales et l'autonomie gouvernementale du peuple tlicho.",
    landParcel: "Bien immobilier représentant l’étendue d'un lot ou d'une parcelle de terrain pour lequel des droits et des intérêts peuvent être enregistrés.",
    inuitOwnedParcel: "Parcelle de terrain représentant l’étendue de terres visées par l’Accord sur les revendications territoriales du Nunavut.",
    inuvialuitFinalParcel: "Parcelle de terrain représentant l’étendue de terres visées par la Convention définitive des Inuvialuit.",
    indianLand: "Terres réservées pour les Indiens au sens du point 24 de l’article 91 de la Loi constitutionnelle de 1867, mais non une réserve au sens de la Loi sur les Indiens.",
    townsite: "Terre dénommée et décrite à l’annexe 4 de la Loi sur les parcs nationaux du Canada.",
    settlementLand: "Place holder",
    nationalPark: "Terre dénommée et décrite à l'annexe 1 de la Loi sur les parcs nationaux du Canada.",
    territorialPark: "Parc établi et maintenu par un gouvernement territorial.",
    ntsQuad: "Division des terres figurant sur les feuillets de quadrilatère du Système national de référence cartographique (SNRC), qui permet la subdivision systématique de zones et l’attribution de numéros d’identification de parcelle uniques à des parcelles.  Les quadrilatères ont d’abord été définis d’après le NAD27, mais le sont aujourd’hui selon le NAD83.",
    unresolved: "Parcelle de terrain ou intérêt dont l’état est « Active » (actif) mais qui ne peut faire géométriquement partie d’autres parcelles d’un même état, car son étendue ou sa situation n’a pas été clairement établie.  Elles se prêtent uniquement aux réserves indiennes.",
    condo: "Bien immobilier représentant l’étendue d’une unité de condominium ou d’un appartement dont les droits ou les intérêts peuvent être enregistrés.  Les zones communes de condominium ne sont pas désignées par cette définition (et ne sont pas représentées dans nos données).",
    strataParcel: "Bien immobilier représentant l’étendue d’une parcelle tridimensionnelle de surface ou souterraine pour laquelle des intérêts peuvent être enregistrés.  Les parcelles stratifiées sont bidimensionnelles dans nos bases de données géospatiales.",
    protectedArea: "Zone de droits publics représentant l’étendue d’un paysage protégé en raison de l’intérêt du public pour celui-ci ou dans l’intérêt commun, y compris des habitats, des aires de nature sauvauge et d’autres zones de gestion spéciales.",
    fieldNoteDescription: "Chaque arpenteur tient avec exactitude et régularité un carnet de notes à l’égard de tous ses arpentages prévus par la Loi sur l'arpentage des terres du Canada; il les produit au bureau de l’arpenteur général dans l’ordre chronologique selon lequel les arpentages ont été effectués. [L.R. (1985), ch. L-6, art. 18]",
    indianReserveDescription: "Des terres cédées ou des réserves au sens de la Loi sur les Indiens.",
    indianReserveFNLMDescription: "Terres réservées pour les Indiens au sens du point 24 de l’article 91 de la Loi constitutionnelle de 1867 ou terres mises de côté au Yukon, pour lesquelles une Première Nation a adhéré à la Loi sur la gestion des terres des Premières Nations.",
    subdivisionDescription: "Étendue d’une subdivision officielle.",    
    oilAndGasSurveyedSSGDescription: "Unité qui consiste en la représentation spatiale d'une unité arpentée.  Il faut noter que l’unité arpentée représente l’étendue de l’unité, non pas celle d’un droit pétrolier et gazier.",
    archivedSurveyLineDescription: "Lignes d'arpentage, établies par un arpenteur-géomètre avec un azimuth et une distance indiqués et référencées par des monuments, qui ont été archivées.",
    otherSurveyedLineDescription: "Les autres lignes arpentées fournissent des renseignements accessoires permettant de mieux déterminer la position d’une limite.  Elles consistent en l’étendue spatiale de données devant être représentées sous forme de lignes, comme des lignes de cheminement, de construction ou des entités topographiques (lignes de côte, courbes de niveau, etc.).",
    lotWithinSettlementDescription: "Parcelle de terrain représentant l’étendue d’une partie d’une parcelle de terrain plus grande qui ne peut être retirée.  Des droits et des intérêts peuvent avoir été enregistrés pour des lots à l'intérieur de terres visées par le règlement.  Ces derniers comprennent les parcelles dans les limites de terres de Première Nation du Yukon.",
    creeLotDescription: "Parcelle de terre des Cris et des Naskapis de la catégorie 1A ou 1A-N.",
    creeLotOtherDescription: "Parcelle de terre des Cris et des Naskapis à l'extérieur des terres du Canada.",
    subGasParcelDescription: "Zone souterraine représentant l’étendue d’une zone de parcelle de droits pétroliers et gaziers souterrains pour laquelle des droits tréfonciers peuvent être enregistrés.",
    easementOtherDescription: "Zone de droits limités représentant l’étendue d’une servitude ou d’une emprise visant un bien immobilier à l'extérieur des terres du Canada.",
    communityDescription: "Étendue d'une communauté dans les 3 territoires du nord telle que définie par la législation territoriale.",
    inconclusiveDescription: "Parcelle de terrain pour laquelle le statut légal n’a pas été clairement établi.  Elles se prêtent uniquement aux réserves indiennes.",
    landParcelOtherDescription: "Bien immobilier représentant l’étendue d'un lot ou d'une parcelle de terrain, qui se trouve à l'extérieur des terres du Canada, pour lequel des droits et des intérêts peuvent être enregistrés.",
    groupDescription: "Division des terres dans les 3 territoires du nord définies sur les plans 60109 CLSR and 79155 CLSR.  Cette segmentation des terres a été utilisée pour fournir un système d'arpentage approprié pour le Nord.  Ce système a été remplacé par les quadrilatères.",
    landExclusionDescription: "Une partie d'une réserve indienne peut être exclue de l'application du code foncier pour des raisons telles que stipulées dans les sections 4.1.4 et 4.1.6 de l'Accord-cadre relatif à la gestion des terres de Premières Nations.",
    designationDescription: "Désigne une réserve ou une partie d'une réserve ou tout intérêt dans celle-ci, dont le titre légal demeure dévolu à Sa Majesté, qui a été libéré ou cédé par le groupe pour lequel utiliser et bénéficier, il a été mis à part.",
    quarterDescription: "Une ligne cadastrale rectiligne représentant plus précisément la limite d'un quart de section de canton arpenté.",
  }
};

let legendViewValue: any = {
  'en-CA': {
    tabToggle: "Show / Hide All Group of Layers",
    allToggle: "Show / Hide All Layers",
    text: "Text",
    basemapToggle: "Basemap",
    archivedLine: "Archived Surveyed Line",
    otherLine: "Other Surveyed Line",
    fieldNote: "Field Notes",
    provisionalLine: "Provisional Line",
    quarterLine: "Quarter Section Line",
    sip: "Survey in Progress",
    placerClaimLine: "Placer Claim Base Line",
    mineralClaimLine: "Mineral Claim Location Line",
    mineralClaimParcel: "Mineral Claim Parcel",
    yukonLot: "Lot Within Settlement Land",
    yukonParcel: "Parcel",
    yukonInternalParcel: "Yukon First Nation Internal Parcel",
    creenaRight: "Right",
    creenaAdminLot: "Administrative Lot",
    creenaParcel: "Cree Naskapi Category 1A and 1AN Parcel",
    creenaBlock: "Block",
    creenaLot: "Lot",
    creenaOther: "Lot - Other",
    irOilGasParcel: "Indian Reserve Surface Oil and Gas Parcel",
    oilGasParcel: "Oil and Gas Parcel",
    grid: "Oil and Gas Grid Area",
    subOilParcel: "Subsurface Oil and Gas Parcel",
    subOilUnit: "Subsurface Oil and Gas Surveyed Unit",
    easement: "Easement",
    easementOther: "Easement - Other",
    inuitOwnedParcel: "Inuit Owned Land Parcel",
    inuvialuitFinalParcel: "Inuvialuit Final Agreement Parcel",
    sahtuParcel: "Sahtu Parcel",
    saltRiverParcel: "Salt River First Nation Parcel",
    tlichoParcel: "Tlicho Parcel",
    gwichinParcel: "Gwich'in Parcel",
    inuitOwnedInternalParcel: "Inuit Owned Land Internal Parcel",
    inuvialuitFinalInternal: "Inuvialuit Final Agreement Internal Parcel",
    ir: "Indian Reserve",
    fnlmIr: " Indian Reserve (under First Nations Land Management Act)",
    otherIr: "Indian Reserve (under Indian Act)",
    il: "Indian Land",
    community: "Community (Territory)",
    townsite: "National Park of Canada Community (Province)",
    settlementLand: "Settlement Land",
    nationalPark: "National Park of Canada",
    territorialPark: "Territorial Park",
    ntsQuad: "NTS Quad",
    subdivision: "Subdivision",
    inconclusive: "Inconclusive Parcel",
    unresolved: "Unresolved Parcel",
    condo: "Condominium",
    strata: "Strata Parcel",
    landParcel: "Land Parcel",
    landParcelOther: "Land Parcel - Other",
    group: "Group",
    protected: "Protected Area",
    landCodeExlcusion: "Land Code Exclusion Area",
    designation: "Designation"
  },
  'fr-CA': {
    tabToggle: "Montrer / masquer tous les groupes de couches",
    allToggle: "Montrer / masquer toutes les couches",
    text: "Texte",
    basemapToggle: "Fond de carte",
    archivedLine: "Ligne d'arpentage archivée",
    otherLine: "Autre ligne d'arpentage",
    fieldNote: "Carnet de notes",
    provisionalLine: "Ligne provisoire",
    quarterLine: "Ligne de quart de section",
    sip: "Arpentage en cours",
    placerClaimLine: "Ligne de base de claim de placer",
    mineralClaimLine: "Ligne d’emplacement de claim minier",
    mineralClaimParcel: "Parcelle de claim minier",
    yukonLot: "Lot à l'intérieur de terres visées par le règlement",
    yukonParcel: "Parcelle",
    yukonInternalParcel: "Parcelle interne",
    creenaRight: "Droit",
    creenaAdminLot: "Lot administratif",
    creenaParcel: "Parcelle de catégorie 1A et 1AN",
    creenaBlock: "Bloc",
    creenaLot: "Lot",
    creenaOther: "Autre lot",
    irOilGasParcel: "Parcelle de surface de droit pétrolier et gazier dans une réserve indienne",
    oilGasParcel: "Droit foncier de pétrole et de gaz",
    grid: "Étendue quadrillée de droit pétrolier et gazier",
    subOilParcel: "Parcelle souterraine de droit pétrolier et gazier",
    subOilUnit: "Unité souterraine arpentée de droit pétrolier et gazier",
    easement: "Servitude",
    easementOther: "Autre servitude",
    inuitOwnedParcel: "Parcelle de terres des Inuits",
    inuvialuitFinalParcel: "Parcelle de terres visées par la Convention définitive des Inuvialuit",
    sahtuParcel: "Parcelle du Sahtu",
    saltRiverParcel: "Parcelle de la Première Nation de Salt River",
    tlichoParcel: "Parcelle du peuple tlicho",
    gwichinParcel: "Parcelle des Gwich’in",
    inuitOwnedInternalParcel: "Parcelle interne de terres des Inuits",
    inuvialuitFinalInternal: "Parcelle interne de terres visées par la Convention définitive des Inuvialuit",
    ir: "Réserve indienne",
    fnlmIr: "Réserve indienne (en vertu de la Loi sur la gestion des terres des Premières Nations)",
    otherIr: " Réserve indienne (en vertu de la Loi sur les Indiens)",
    il: "Terre indienne",
    community: "Collectivité (territoire)",
    townsite: "Collectivité de parc national du Canada (province)",
    settlementLand: "Terre octroyée par l'entente",
    nationalPark: "Parc national du Canada",
    territorialPark: "Parc territorial",
    ntsQuad: "Quadrilatère SNRC",
    subdivision: "Subdivision",
    inconclusive: "Parcelle non concluante",
    unresolved: "Parcelle non résolue",
    condo: "Condominium",
    strata: "Parcelle stratifiée",
    landParcel: "Parcelle",
    landParcelOther: "Autre parcelle",
    group: "Groupe",
    protected: "Aire protégée",
    landCodeExlcusion: "Zone d'exclusion du code foncier",
    designation: "Designation"
  }
}

let currentLang: string = document.documentElement.lang;
export const legendTextElem: any = legendDescriptions[currentLang];
export const legendViewElem: any = legendViewValue[currentLang];
